spring.application.name=order-service
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=5671
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}
spring.rabbitmq.virtual-host=${RABBIT_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8082}