spring.application.name=order-service
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tqohcawi
spring.rabbitmq.password=3d0MqF3wp1x0CH9sJ1lN8Uiry3jwOGQc
spring.rabbitmq.virtual-host=tqohcawi
spring.rabbitmq.ssl.enabled=true